# Learning pytorch

## Tensors


In [3]:
# where it all begins...the innocent vector
a = [1, 2, 3]
a

[1, 2, 3]

In [6]:
import torch
a = torch.ones(3)
print(a)
print(a[0])

tensor([1., 1., 1.])
tensor(1.)


In [9]:
points = torch.tensor([[1,2], [3,4], [6,9]])
print(points)
points.shape

tensor([[1, 2],
        [3, 4],
        [6, 9]])


torch.Size([3, 2])

In [46]:
points

tensor([[1, 2],
        [3, 4],
        [6, 9]])

In [45]:
torch.randn(1,3,5,6)

tensor([[[[ 1.0668, -1.0812, -0.6291,  0.3592, -0.3375,  0.4889],
          [ 0.3901, -1.1137, -0.5904, -1.2772, -0.1168, -0.1316],
          [-0.1472, -1.6614, -1.5264, -0.1616, -0.2030,  0.5750],
          [-0.3974, -0.5479,  0.8834, -0.7721, -0.7097, -0.7588],
          [-0.4560, -1.1754, -0.6510,  0.4799, -0.2176, -1.0985]],

         [[ 1.5334,  0.6469, -0.1491, -0.5866,  0.3154, -2.8772],
          [-0.2438, -0.6264,  1.0449, -0.0902,  0.8562,  0.8362],
          [-2.6036,  0.6465, -0.5956,  1.1516,  0.8328,  0.0450],
          [ 0.4365,  1.5059, -0.4002, -1.4430,  0.6134, -0.2582],
          [-1.9307,  0.7267,  1.6412, -0.4672,  1.1423, -0.5179]],

         [[-0.0541, -0.2765,  0.9911,  1.5698,  0.0382,  1.4972],
          [-1.7186, -0.3854, -0.8562, -0.8509,  1.1160,  1.3524],
          [-0.1884, -0.4587, -1.2948, -0.2401,  0.2441,  0.1679],
          [ 0.0671, -1.4095,  0.7467,  0.3764,  1.1534, -0.2272],
          [ 1.1148,  0.4300,  1.6242, -2.3581,  0.0588, -1.3865]]]])

In [48]:
torch.tensor([1,2,3], names=("hi",))

ipykernel_launcher:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:934.)


tensor([1, 2, 3], names=('hi',))

### tensor operations


In [51]:
a = torch.tensor([[1,2],[3,4]])
a

tensor([[1, 2],
        [3, 4]])

In [63]:
# takes in dimensions to swap. (0,1) will be same as (1,0)
a.transpose(0,1)

tensor([[1, 3],
        [2, 4]])

In [64]:
a.storage()

 1
 2
 3
 4
[torch.LongStorage of size 4]

## exercises


In [66]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
a.shape, a.storage_offset(), a.stride()

(torch.Size([9]), 0, (1,))

In [71]:
b  =  a.view(3,  3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [74]:
id(b.storage()) == id(a.storage())

True

In [77]:
c = b[1:, 1:]
c

tensor([[4, 5],
        [7, 8]])

In [79]:
c.size(), c.storage_offset(), c.stride()

(torch.Size([2, 2]), 4, (3, 1))

In [83]:
torch.sin(a)

tensor([ 0.0000,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589, -0.2794,  0.6570,
         0.9894])